language: node_js
node_js:
  - "11"
install:
  - cd docs && npm install
script:
  - cd docs && npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  repo: lakermann/ar-with-unity-workshop
  keep-history: false
  target-branch: gh-pages
  on:
    branch: master
